
# cargo-vet audits file

[[audits.gtk4-macros]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.10.0 -> 0.10.1"
notes = "No actual code changes"

[[audits.hashbrown]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.14.3 -> 0.14.5"

[[audits.memchr]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "2.7.2 -> 2.7.5"

[[audits.memchr]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "2.7.5 -> 2.7.6"

[[audits.serde_spanned]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.6.7 -> 0.6.9"

[[audits.serde_spanned]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.6.9 -> 1.0.3"

[[audits.slab]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.4.8 -> 0.4.9"

[[audits.slab]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.4.9 -> 0.4.10"

[[audits.slab]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.4.10 -> 0.4.11"

[[trusted.cairo-rs]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-07-08"
end = "2026-07-03"

[[trusted.cairo-sys-rs]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-10-16"
end = "2026-07-16"

[[trusted.cairo-sys-rs]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2023-07-23"
end = "2026-07-16"

[[trusted.gdk-pixbuf]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-07-16"

[[trusted.gdk-pixbuf]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2023-07-23"
end = "2026-07-16"

[[trusted.gdk-pixbuf-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-07-16"

[[trusted.gdk-pixbuf-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2023-07-23"
end = "2026-07-16"

[[trusted.gdk4]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-09-22"

[[trusted.gdk4]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gdk4-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-09-22"

[[trusted.gdk4-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gdk4-wayland]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-06-06"

[[trusted.gdk4-wayland]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gdk4-wayland-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-06-06"

[[trusted.gdk4-wayland-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gdk4-x11]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-06-06"

[[trusted.gdk4-x11]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gdk4-x11-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-06-06"

[[trusted.gdk4-x11-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gio]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-08-28"
end = "2026-07-03"

[[trusted.gio-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-09-16"
end = "2026-07-16"

[[trusted.gio-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2023-07-23"
end = "2026-07-16"

[[trusted.glib]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-02-14"
end = "2026-07-03"

[[trusted.glib-macros]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-07-08"
end = "2026-07-03"

[[trusted.glib-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-09-16"
end = "2026-07-16"

[[trusted.glib-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2023-07-23"
end = "2026-07-16"

[[trusted.gobject-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-07-16"

[[trusted.gobject-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2023-07-23"
end = "2026-07-16"

[[trusted.graphene-rs]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-07-16"

[[trusted.graphene-rs]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2023-07-23"
end = "2026-07-16"

[[trusted.graphene-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-07-16"

[[trusted.graphene-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2023-07-23"
end = "2026-07-16"

[[trusted.gsk4]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-09-22"

[[trusted.gsk4]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gsk4-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-09-22"

[[trusted.gsk4-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gtk4]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-07-03"

[[trusted.gtk4]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gtk4-macros]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gtk4-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-09-22"

[[trusted.gtk4-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.libadwaita]]
criteria = "safe-to-run"
user-id = 111887 # Maximiliano (A6GibKm)
start = "2025-03-19"
end = "2026-07-16"

[[trusted.libadwaita-sys]]
criteria = "safe-to-run"
user-id = 111887 # Maximiliano (A6GibKm)
start = "2025-03-19"
end = "2026-07-16"

[[trusted.libc]]
criteria = "safe-to-run"
user-id = 55123 # rust-lang-owner
start = "2024-08-15"
end = "2026-07-03"

[[trusted.pango]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-08-11"
end = "2026-07-03"

[[trusted.pango-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-07-16"

[[trusted.pango-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2023-07-23"
end = "2026-07-16"

[[trusted.syn]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-07-16"

[[trusted.toml]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2022-12-14"
end = "2026-07-16"

[[trusted.toml_edit]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2021-09-13"
end = "2026-07-16"

[[trusted.windows-sys]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2026-07-16"

[[trusted.windows-targets]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2026-07-16"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2026-07-16"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2026-07-16"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2026-07-16"

[[trusted.windows_i686_gnullvm]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-04-02"
end = "2026-07-16"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2026-07-16"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2026-07-16"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2026-07-16"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2026-07-16"

[[trusted.winnow]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2023-02-22"
end = "2026-07-16"
